pages/urls.py
from django.urls import path
from .views import HomePageView, AboutPageView, youtube


urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    path('about', AboutPageView.as_view(), name='about'),
    path('youtube', youtube, name='youtube'),

]

posts/urls.py
from django.urls import path
from .views import PostView, post_detail, add_post ,update_post, delete_post, update_comment, delete_comment

app_name = 'posts'
urlpatterns = [
    path('<int:id>/<int:id1>/delete', delete_comment, name='delete_comment'),
    path('<int:id>/<int:id1>/update', update_comment, name='update_comment'),
    path('<int:id>/delete', delete_post, name='delete_post'),
    path('<int:id>', update_post, name='update_post'),
    path('add_post', add_post, name='add_post'),
    path('', PostView, name='allposts'),
    path('<int:id>/', post_detail, name='post_details')
]

posts/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from pytz import timezone
from sqlalchemy import null

# Create your models here.
class Post(models.Model):
    title = models.CharField(
        max_length=400,
        help_text=_("Required: max-400"),
        verbose_name=_("title")
    )

    text = models.TextField(_("text"))
    image = models.ImageField(
        _("image"),
        upload_to='uploads/',
        help_text=_("can be empty")
    )

    author = models.ForeignKey(
        get_user_model(),
        on_delete=models.PROTECT
    )

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('book_detail', kwargs={'pk': str(self.pk)})


class Comment(models.Model):
    post = models.ForeignKey(Post,
        on_delete=models.CASCADE,
        related_name="comments"
    )
    comment = models.TextField(max_length=1000)
    author = models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE,
    )

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.comment[:30]

    class Meta:
        ordering = ['created_at']

    def get_absolute_url(self):
        return reverse('posts')

class Reply(models.Model):
    comment = models.ForeignKey(Comment,
        on_delete=models.CASCADE,
        related_name="replys"
    )
    text = models.TextField(max_length=500)
    author = models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE,
    )

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.text[:20]

    class Meta:
        ordering = ['created_at']

posts/forms.py
from django import forms
from .models import Post, Comment, Reply

class AddPostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = [
            'title',
            'text',
            'image',
        ]

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['comment']

class CommentUForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['comment']

class search_post(forms.Form):
    q = forms.CharField()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['q'].label = 'Search For'
        self.fields['q'].widget.attrs.update(
            {'class': 'form-control'}
        )

class ReplyForm(forms.ModelForm):
    class Meta:
        model = Reply
        widgets = {
          'text': forms.Textarea(attrs={'rows':1, 'cols':5}),
        }
        fields = ['text']
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['text'].label = ""
        

posts/views.py
from pyexpat import model
from webbrowser import get
from django.shortcuts import render, redirect, get_object_or_404, reverse
from django.views.generic import TemplateView, UpdateView
from .models import Post, Comment
from .forms import AddPostForm, CommentForm, search_post, CommentUForm, ReplyForm
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.urls import reverse

# Create your views here.

def PostView(request):
    form = search_post
    posts = Post.objects.all().order_by('-created_at')

    #search
    if 'q' in request.GET:
        form = search_post(request.GET)
        if form.is_valid():
            q = form.cleaned_data['q']
            
            posts = Post.objects.filter(title__icontains=q).order_by('-created_at')

    #pagination
    page = request.GET.get('page', 1)

    paginator = Paginator(posts, 9)
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

            
    
    
    return render(request, 'posts/posts.html', {'form':form,'posts': posts})

def post_detail(request, id):
    post = get_object_or_404(Post, pk=id)
    
    
    new_comment = None
    new_reply = None
    comment_form = CommentForm()
    reply_form = ReplyForm()
    # Comment posted
    
    if request.method == 'POST':
        if request.POST.get('form_type') == 'comment':
            comment_form = CommentForm(data=request.POST)
            if comment_form.is_valid():

                # Create Comment object but don't save to database yet
                new_comment = comment_form.save(commit=False)
                # Assign the current post to the comment
                new_comment.post = post
                new_comment.author = request.user
                # Save the comment to the database
                new_comment.save()
                return redirect('posts:post_details', id)
                # return render(request, 'posts/post_details.html')
            
        else:
            # request.POST.get('form_type') == 'reply':
            reply_form = ReplyForm(data=request.POST)
            if reply_form.is_valid():
                # Create Comment object but don't save to database yet

                parent_id = int(request.POST.get('form_type'))
                new_reply = reply_form.save(commit=False)
                # Assign the current post to the comment
                new_reply.comment = get_object_or_404(Comment, id=parent_id)
                new_reply.author = request.user
                # Save the comment to the database
                new_reply.save()
                print(parent_id)
                return redirect('posts:post_details', new_reply.comment.post_id)

                # return render(request, 'posts/post_details.html')
    
    else:
        return render(request,'posts/post_details.html', {'post': post,
                                           'comment_form': comment_form,
                                           'reply_form': reply_form,}
                )

@login_required
def add_post(request):
    context ={}
    form = AddPostForm(request.POST ,request.FILES)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.author = request.user
        instance.save()

        return redirect('posts:post_details', instance.pk)


    context['form'] = form

    return render(request, 'posts/add_post.html', context)

def update_post(request, id):
        # dictionary for initial data with
    # field names as keys
    context = {}
 
    # fetch the object related to passed id
    obj = get_object_or_404(Post, id = id)
 
    # pass the object as instance in form
    form = AddPostForm(request.POST or None, instance = obj)
 
    # save the data from the form and
    # redirect to detail_view
    if form.is_valid():
        form.save()
        return redirect('posts:post_details', id)
 
    # add form dictionary to context
    context["form"] = form
 
    return render(request, "posts/update_view.html", context)

def delete_post(request, id):
    # dictionary for initial data with
    # field names as keys
    context ={}
 
    # fetch the object related to passed id
    obj = get_object_or_404(Post, id = id)
 
 
    if request.method =="POST":
        # delete object
        obj.delete()
        # after deleting redirect to
        # home page
        return redirect("posts:allposts")
    context['post'] = obj
 
    return render(request, "posts/delete_view.html", context)


def update_comment(request, id, id1):

    context = {}
    obj = get_object_or_404(Comment, id=id1)
    form = CommentUForm(request.POST or None, instance= obj)
    if form.is_valid():
        form.save()
        return redirect('posts:post_details', id)
    context['form'] = form

    return render(request, 'posts/update_comment.html', {'form': form})

def delete_comment(request, id, id1):
    context = {}
    obj = get_object_or_404(Comment, id=id1)

    if request.POST:
        obj.delete()
        return redirect('posts:post_details', id)
    
    context['post'] = id
    print(context)
    return render(request, "posts/delete_comment.html", context)
    

templates/posts/add_post.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Add post{% endblock title %}

{% block content %}
 <div class="container">
     <h1 class="text-center">Add A Post</h1>
     <div class="addfrom mb-3">
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token%}
            {{form|crispy}}
    
            <div class="button text-center">
                <button class="btn btn-primary" type="submit">Add Post</button>
                <a href="{% url 'posts:allposts' %}" class="btn btn-secondary" type="button">Cancel</a>
            </div>
        </form>
     </div>
 </div>

{% endblock content %}

templates/posts/delete_comment.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Delete post{% endblock title %}

{% block content %}
 <div class="container" style="height: 100vh;">
     <h1 class="text-center">Delete Comment</h1>
     <div class="addfrom mb-3">
        <form action="" method="post">
            {% csrf_token %}
            <p class="text-center">Are you sure you want to delete this comment?</p>
            <div class="button text-center">
                <a type="button" class="btn btn-secondary my-2" href="{% url 'posts:post_details' post %}">Cancel</a>
                <button class="btn btn-danger" type="submit">Delete</button>
                
            </div>
        </form>
     </div>
 </div>
    
{% endblock content %}

templates/posts/delete_view.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Add post{% endblock title %}

{% block content %}
 <div class="container">
     <h1 class="text-center">Delete Post</h1>
     <div class="addfrom mb-3">
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <p class="text-center">Are you sure you want to delete this post?</p>
            <div class="button text-center">
                <a class="btn btn-secondary my-2" href="{% url 'posts:allposts' %}">Cancel</a>
                <button class="btn btn-danger" type="submit">Delete</button>
                
            </div>
        </form>
     </div>
 </div>
    
{% endblock content %}

templates/posts/post_details.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}Post Details{% endblock title %}

{% block content %}
<div class="container" style="color:black">
    <div class="row">
        <div class="col-md-10 my-5">
            
            <div class="card " >
                <div class="card-header">
                    <p >Author: <span class="text-success"> {{post.author}}</span> Asked the question on <span class="text-success"> {{post.created_at}}</span></p>
                </div>
                <div class="card body" style="text-align: justify; padding-left: 10px">
                    <h2 class="card-title">{{post.title}}</h2>
                    <p class="card-text">{{post.text}}</p>
                    
                </div>
                <img src="{{post.image.url}}" class="img-responsive" style="width: 100%" alt="image"/>
            </div>
        
            <h3 class="text-info my-3"><i class="fa fa-comments" aria-hidden="true"></i> Comments</h3>
            <div class="comments">
                {% if post.comments.all %}
                {% for comment in post.comments.all %}
                <div class="comment ml-5 mb-5 card">
                    <div class="card-header">
                        <div class="row">
                            <div class="col-md-6">
                                <img src="{% static 'images/avatr2.jpg' %}" alt="image" style="width: 50px; border-radius: 50%">
                                <p class="text">{{comment.author}}</p>
                                <p> <span class="text-success">{{comment.updated_at}}</span></p>
                            </div>
                            <div class="col-md-6">
                                
                            </div>
                        </div>
                    </div>
                    <div class="card-body">
                        <p class="card-text">{{comment.comment}}</p>
                    </div>
                    <div class="card-footer">
                        

                        {% if user.is_authenticated and user == comment.author %}
                        <div class="row">
                            <div class="col-md-10">       
                            </div>
                            <div class="col-md-2">
                                <a href="{{comment.pk}}/update" class="btn btn-outline-warning btn-sm" type="button"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></a>
                                <a href="{{comment.pk}}/delete" class="btn btn-outline-danger btn-sm" type="button"><i class="fa fa-trash-o" aria-hidden="true"></i></a>
                            </div>
                        </div>
                        
                        {% endif %}
                        <div class="rep">
                            
                            {% if user.is_authenticated %}
                                            
                                
                                    <form method="post" style="margin-top: 1.3em;">
                                        {% csrf_token %}
                                        <div class="row">
                                        <div class="col-md-8">
                                            {{ reply_form|crispy }}
                                            <input type="hidden" name="form_type" value="{{comment.id}}">          
                                        </div>
                                        <div class="col-md-4">
                                            <button type="submit" class="btn btn-info  btn-sm mt-1">Reply</button>
                                        </div>
                                        </div>
                                    </form>
                                
                            {% else %}
                                <p>Login to reply</p>
                            {% endif %}
                        </div>
                        
                    {% if comment.replys.all%}
                    <h4 class="text-info"><i class="fa fa-reply" aria-hidden="true">Replies</i></h4>
                    {% endif %}
                        
                    </div>
                    {%for r in comment.replys.all %}
                        <div class="replys ml-5 mr-5">
                            
                            <div class="card my-2 shadow-sm">
                                <div class="row d-flex align-items-center">
                                    <div class="col-md-2">
                                        <div class="card-head mt-2">
                                            <img src="{% static 'images/avatr2.jpg' %}" alt="image" style="width: 40px; border-radius: 50%">
                                            <p class=" p-1 text-success" >{{r.author}}:</p>
                                        </div>
                                    </div>

                                    <div class="col-md-10">
                                        <div class="card-bod m-2" style="text-align: start; padding: 2px">
                                            <p class="card-text ">{{r.text}}</p>
                                        </div>
                                    </div>
                                </div>
                                
                            </div>
                        </div>
                    {% endfor %}
                </div>
                {% endfor %}

                {% else %}
                <div class="comment ml-5 mb-5">
                    <p style="color: whitesmoke;" class="text-alert">No Comments Yet! <span style="font-size: 28px"> &#x1F625; </span></p>
                    
                </div>

                {% endif %}
            </div>

            {% if user.is_authenticated %}
            <div class="col-md-8 card mb-4  mt-3 " style="color: black;">
            <div class="card-body">
                <h3>Leave an answer</h3>
                <form method="post" style="margin-top: 1.3em;">
                    {% csrf_token %}
                  {{ comment_form|crispy }}
                  <input type="hidden" name="form_type" value="comment">
                  <button type="submit" class="btn btn-info  btn-lg">Submit</button>
                </form>
              </div>
            </div>
              {% endif %}
        </div>
        <div class="side col-md-2 my-3">
            <div class="card">
                <div class="card-header">
                    <a href="{% url 'youtube' %}"><i class="fa fa-youtube-play" aria-hidden="true"></i>Search</a> <br>
                    <a href="{% url 'posts:allposts' %}"> <<--posts</a>
                    <br>
                    {% if user.is_authenticated and user == post.author %}
                    <a class="btn btn-warning my-1" href="{% url 'posts:update_post' id=post.pk %}">Update Post</a>
                    <br>
                    <a class="btn btn-danger my-1" href="{% url 'posts:delete_post' id=post.pk %}">Delete Post</a>
                    {% endif %}
                </div>
                <div class="card-body">
                    <h2 class="card-title text-info">Our Blog ckeck out our recent posts</h2>
                    <p class="text"></p>
                </div>
                <div class="card-footer">
                    <h3 class="text-info">
                        OurCom
                    </h3>
                </div>
            </div>
        </div>

    </div>
</div>

<script>
    
</script>
{% endblock content %}

templates/posts/posts.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Posts{% endblock title %}
{% block content %}
<div class="container">
  <div class="row">
    <div class="col-md-"></div>
    <div class="col-md-4">
      <div class="search" style="width: fit-content">
        <form  method="GET">
          <div class="div" style="display: flex; align-items:center">
            <div class="input">
              {{form.as_p}}
            </div>
            <div class="button mt-3">
              <input class="btn btn-primary" type="submit" value="Search">
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
  
    <div class="row">
        
      <div class="col-md-10">
        <p class="text-success my-3">Recent Posts</p>
      </div>
      <div class="col-md-2 my-2">
        <a class="btn btn-primary" href="{% url 'posts:add_post' %}">Post A question</a>
      </div>
    </div>

    
    <div class="row">
      {% if posts %}
        {% for post in posts %}
        
        <div class="col-md-4">
          <a href="{% url 'posts:post_details' id=post.pk %}" class="text-dark">
            <div class="card mb-4 box-shadow bg-light">
              <div class="card-body">
                <h2 style="font-size:15px; font-weight: bold">{{post.title|truncatechars:50}}</h2>
                
                <h2 style="font-size:15px">{{post.text|truncatechars:50}}....</h2>
                <div class="d-flex justify-content-between align-items-center">
                  <small class="text-muted">{{post.author}}</small>
                </div>
              </div>
            </div>
          </a>
        </div>
        {% endfor %}
      {% else %}
        <div>
          <h4>post not found!</h4>
        </div>
      {% endif %}
    </div>


   <div class="page" style="width: 40%; margin: auto; font-size: 30px;">
    <div class="text-center ">
      {% if posts.has_other_pages %}
      <ul class="pagination">
        {% if posts.has_previous %}
          <li><a href="?page={{ posts.previous_page_number }}">&laquo;</a></li>
        {% else %}
          <li class="disabled"><span>&laquo;</span></li>
        {% endif %}
        {% for i in posts.paginator.page_range %}
          {% if posts.number == i %}
            <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
          {% else %}
            <li><a href="?page={{ i }}">{{ i }}</a></li>
          {% endif %}
        {% endfor %}
        {% if posts.has_next %}
          <li><a href="?page={{ posts.next_page_number }}">&raquo;</a></li>
        {% else %}
          <li class="disabled"><span>&raquo;</span></li>
        {% endif %}
      </ul>
    {% endif %}
    </div>
   </div>  
  </div


{% endblock content %}

templates/posts/update_comment.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container">
    <h1 class="text-center">Update comment</h1>
    <div class="form my-5">
        <form action="" method="post">
            {% csrf_token %}
            {{form|crispy}}
    
            <button class="btn btn-warning" type="submit">Update</button>
        </form>
    </div>
</div>
{% endblock content %}

templates/posts/update_view.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Update Post{% endblock title %}

{% block content %}
 <div class="container">
     <h1 class="text-center">Update post</h1>
     <div class="addfrom mb-3">
        <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token%}
            {{form|crispy}}
    
            <div class="button text-center">
                <button class="btn btn-primary" type="submit">Update</button>
            </div>
        </form>
     </div>
 </div>
    
{% endblock content %}