pages/urls.py
from django.urls import path
from .views import HomePageView, AboutPageView, youtube


urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    path('about', AboutPageView.as_view(), name='about'),
    path('youtube', youtube, name='youtube'),

]

posts/urls.py
from django.urls import path
from .views import PostView, post_detail, add_post ,update_post, delete_post, update_comment, delete_comment

app_name = 'posts'
urlpatterns = [
    path('<int:id>/<int:id1>/delete', delete_comment, name='delete_comment'),
    path('<int:id>/<int:id1>/update', update_comment, name='update_comment'),
    path('<int:id>/delete', delete_post, name='delete_post'),
    path('<int:id>', update_post, name='update_post'),
    path('add_post', add_post, name='add_post'),
    path('', PostView, name='allposts'),
    path('<int:id>/', post_detail, name='post_details')
]

templates/pages/about.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
 <div class="container">
    <div class="row ">
        <div class="col-md-12 mt-3">
            <h1 class="text-center text-info" style="font-family: Noto serif display"> OurCom</h1>
            <p class="text-center">By helping others we are making this world a better place. Let this platform encourage you to assist and support others whenever you can..</p>
        </div>
    </div>
    <div class="row d-flex justify-content-center" style="display: flex; align-items: center">
        <div class="col-md-4">
            <div class="image" style="width: 90px;">
                <img style="border-radius: 20px; height: 400px; width: auto" class="img-responsive" src="{% static 'images/ourh.png' %}" alt="" >
            </div>
        </div>
        <div class="col-md-8 ">
            <h3 class="text-info" style="font-family: Noto serif display" >Share</h3>
            <p>We learn and understand more when we try to teach and explain to others what we understand about a particular concept.</p>
        </div>
    </div>

    <div class="row d-flex justify-content-center" style="display: flex; align-items: center">
        
        <div class="col-md-6 ">
            <h3 class="text-info" style="font-family: Noto serif display" >Observe</h3>
            <p>Dont make the same mistakes other people already did . Learn from other people mistakes and how they tackled the problems they encountered.</p>
        </div>
        <div class="col-md-6">
            <div class="image" style="width: 90px;">
                <img style="border-radius: 20px; height: 400px; width: auto" class="img-responsive" src="{% static 'images/ours.png' %}" alt="" >
            </div>
        </div>
    </div>

    <div class="row d-flex justify-content-center" style="display: flex; align-items: center">
        <div class="col-md-4">
            <div class="image" style="width: 90px;">
                <img style="border-radius: 20px; height: 400px; width: auto" class="img-responsive" src="{% static 'images/ourcr.png' %}" alt="" >
            </div>
        </div>
        <div class="col-md-8 ">
            <h3 class="text-info" style="font-family: Noto serif display" >Reach Out</h3>
            <p >Look for answers when you are stuck dont forget to ask because a problem shared i a half way solved. remember this is our community (OurCom)</p>
        </div>
    </div>

    <h1 class="text-center mt-5 text-info" style="font-family: Noto serif display">Project Details</h1>
    <div class="row mb-5">
        
        <div  class="col-md-6">
            <h3 style="font-family: Noto serif display" class="text-center">Location</h3>
            <ul>
                <li style="font-size: 28px;">Name: OurCom</li>
                <li style="font-size: 28px;">Github: <a href="https://github.com/Collin-5/website_ourcom"><i  class="fa fa-github " aria-hidden="true"></i></a></li>
            </ul>

        </div>
        <div class="col-md-6">
            <h3 style="font-family: Noto serif display" class="text-center">Developer</h3>
            <ul>
                <li style="font-size: 28px;">Name: Collins Otieno</li>
                <li style="font-size: 28px;">Github: <a href="https://github.com/Collin-5"><i  class="fa fa-github " aria-hidden="true"></i></a></li>
            </ul>
        </div>
    </div>
 </div>
{% endblock content %}

templates/pages/index.html
{% extends 'base.html' %}

{% block title %}Home Page{% endblock title %}
{% block content %}
  <div class="container" style="height: 100vh;">
    <div class="jumbotron text-center" style="color: black; margin-top: 30px">
      {%if user.is_authenticated %}
      <h1 class="display-4" style="font-family: Noto serif display">Hello, {{user.username}}!</h1>
      {% else %}
      <h1 class="display-4" style="font-family: Noto serif display">Hello!</h1>
      {% endif %}

      <p class="lead">	
        By helping others we are making this world a better place. Let this platform encourage you to assist and support others whenever you can..</p>
      <hr class="my-8">
      <p>Get started, answer or post a question bellow.</p>
      <p class="lead">
        <a class="btn btn-primary btn-lg" href="{% url 'posts:allposts' %}" role="button">Questions</a>
      </p>
    </div>
  </div>
{% endblock content %}

templates/pages/nav.html
{% block header %}
<nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
    <a class="navbar-brand" href="{% url 'home' %}">OurCom</a><button class="navbar-toggler" type="button" data-toggle="collapse"
    data-target="#navbarCollapse" aria-controls="navbarCollapse"
    aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
    {% if user.is_authenticated %}
    <ul class="navbar-nav ml-auto">
    <li class="nav-item">
    <a class="nav-link dropdown-toggle" href="#" id="userMenu"
    data-toggle="dropdown" aria-haspopup="true"
    aria-expanded="false">
    {{ user.username }}
    </a>
    <div class="dropdown-menu dropdown-menu-right"
    aria-labelledby="userMenu">
    <a class="dropdown-item"
    href="#">Change password</a>
    <div class="dropdown-divider"></div>
    <a class="dropdown-item" href="{% url 'logout' %}">
    Log Out</a>
    </div>
    </li>
    </ul>
    {% else %}
    <form class="form-inline ml-auto">
    <a href="#" class="btn btn-outline-secondary">
    Log In</a>
    <a href="#" class="btn btn-primary ml-2">
    Sign up</a>
    </form>
    {% endif %}
    </div>
</nav>
{% endblock header %}

templates/pages/youtube.html
{% extends 'base.html' %}
{% load static %} 
{% load crispy_forms_tags %}
{% block content %}
<section style="margin-bottom: 200px;" class='text-center container'>
    <h2 class="mt-4">Search For solutions From Youtube</h2>
    <p>search videos and select any video to open in youtube</p>
    <form action="" method="post">
        {% csrf_token %}
        {{form}}
        <input class="btn btn-danger" type="submit" value="Submit">
    </form><br>

    {% for result in results %}
    <a href="{{result.link}}" target="_blank">
        <div class="card">
            <div class="card-header">
                <div class="row">
                    <div class="col-md-5">
                        <img class="img-fluid" src="{{result.thumbnail}}" alt="">

                    </div>
                    <div class="col-md-7">
                        <h3 class="p-0 m-0">{{result.title}}</h3>
                        <b>
                            <u>
                                <h5 class="p-0 m-0">{{result.channel}}</h5>
                            </u>
                        </b>
                        <h6 class="p-0 m-1">{{result.description}}</h6>
                        <b>
                            <h6 class="ml-0 mt-3">{{result.duration}}</h6>
                            <h6 class="ml-0 mt-1">{{result.views}}</h6>
                            <h6 class="ml-0 mt-1">{{result.published}}</h6>
                        </b>
                    </div>
                </div>
            </div>
        </div>
    </a>
    <br>
    {% endfor %}
</section>

{% endblock content %}